version: '3.7'
services:
    chrome:
        image: selenium/standalone-chrome:latest
        networks: 
            - seleniumgrid
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub

    firefox:
        image: selenium/standalone-firefox:latest
        networks: 
            - seleniumgrid        
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
    hub:
        image: selenium/hub
        networks: 
            - seleniumgrid        
        ports:
            - "4444:4444"

networks:
    seleniumgrid:
        name: seleniumgrid
                    